# Digital Ocean App Platform Specification
# Blog-Poster FastAPI Backend Production Configuration
name: blog-poster-api
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DEPLOYMENT_LIVE
  - rule: DOMAIN_FAILED
  - rule: DOMAIN_LIVE

# Enable buildpack features
features:
  - buildpack-stack=ubuntu-22

# Ingress configuration
ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /
      cors:
        allow_origins:
          - prefix: https://blog-poster.vercel.app  # Your Vercel frontend
          - prefix: https://servicedogus.com
          - prefix: http://localhost:3000  # Local development
          - prefix: http://localhost:5173  # Vite development
        allow_methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        allow_headers:
          - Authorization
          - Content-Type
          - X-API-Key
          - X-Organization-ID
        allow_credentials: true

services:
  - name: api
    dockerfile_path: Dockerfile.light
    source_dir: /
    
    # GitHub integration
    github:
      repo: anthonyscolaro/blog-poster.projectassistant.ai
      branch: main
      deploy_on_push: true
    
    # Resource allocation
    instance_size_slug: professional-xs  # 1 vCPU, 2GB RAM, $25/month
    instance_count: 1
    
    # HTTP configuration
    http_port: 8088
    
    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Run command
    run_command: uvicorn app:app --host 0.0.0.0 --port 8088
    
    # Environment variables
    envs:
      # Public environment variables
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO
      
      - key: WORDPRESS_URL
        scope: RUN_TIME
        value: https://servicedogus.com
      
      - key: WP_VERIFY_SSL
        scope: RUN_TIME
        value: "true"
      
      - key: MAX_COST_PER_ARTICLE
        scope: RUN_TIME
        value: "0.50"
      
      - key: MAX_MONTHLY_COST
        scope: RUN_TIME
        value: "100.00"
      
      - key: ALLOWED_ORIGINS
        scope: RUN_TIME
        value: "https://blog-poster.vercel.app,https://servicedogus.com"
      
      # Secret environment variables - Blog-Poster Backend Database
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: "postgresql://postgres.epftkydwdqerdlhvqili:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZnRreWR3ZHFlcmRsaHZxaWxpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTI4NDU0MCwiZXhwIjoyMDcwODYwNTQwfQ.vM4-DdBqqQh9KfsHmuxKlXyNHMVyZ60qZ6kmXHW7k9o@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
      
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: "https://pynlhikthsmduttvihuw.supabase.co"
      
      - key: SUPABASE_ANON_KEY
        scope: RUN_TIME
        type: SECRET
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bmxoaWt0aHNtZHV0dHZpaHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzODIwMTYsImV4cCI6MjA3MDk1ODAxNn0.BDGAvf1jeX9iiQF7RaouCyzds6NS58guKB4l39AX_uQ"
      
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bmxoaWt0aHNtZHV0dHZpaHV3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTM4MjAxNiwiZXhwIjoyMDcwOTU4MDE2fQ._hyfVCT8sAMVKPZkqjxu3RMW7fX2BEofW05H9G1tSrM"
      
      - key: SUPABASE_JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: "CcGUZqo8ZdqMD2pNUCNN"
      
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: JINA_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: WP_USERNAME
        scope: RUN_TIME
        type: SECRET
      
      - key: WP_APP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET