# Minimal nginx reverse proxy for completing coldknock deployment
# This creates the missing infrastructure component

version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    environment:
      - ENABLE_IPV6=true

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/acme.sh
    restart: unless-stopped
    networks:
      - reverse-proxy-network
    environment:
      - DEFAULT_EMAIL=admin@projectassistant.ai
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acme:

networks:
  reverse-proxy-network:
    name: reverse-proxy-network
    external: false